name: IngotWarn
main: com.budderman18.IngotWarn.main
version: 1.1
commands:
   warn:
       description: Send a warn to an online or offline player
       default: op
       usage: /warn [player] [reason]
   checkwarns:
       description: Check your warns
       default: true
       usage: /checkwarns (player)
   adminwarn:
       description: Access admin management for IngotWarn
       default: op
       usage: /adminwarn [command]
permissions:
   ingotwarn.warn:
      description: Gives access to the warn command
      default: op
   ingotwarn.checkwarns:
      description: Gives access to the checkwarns command
      default: true
   ingotwarn.adminwarn:
      description: Gives access to the adminwarn command
      default: op
   ingotwarn.checkwarns.others:
      description: Gives access to checking other peoples' warns
      default: op